name: TEST

on:
  workflow_dispatch:
    secrets:
      wp_host: 'host'
      health_safety_url: null

jobs:
  test:
    name: TEST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build web
        env:
          TT: ${{ secrets.health_safety_url == null && format('{0}/health-guidance-training-information', secrets.wp_host) || format('{0}/{1}', secrets.wp_host, secrets.health_safety_url) }}
        run: echo ${{ env.TT }}


