name: TEST

on:
  workflow_dispatch:

jobs:
  test:
    name: TEST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: echo ${{ secrets.TEST_SECRET }} == "SECRET"