name: TEST

on:
  workflow_call:
    inputs:
      mode:
        type: string
        required: false
        default: 'production'
      version:
        type: string
        required: false
        default: ${{ github.sha }}
    secrets:
      wp_host:
        required: true
      health_safety_url:
        required: true

jobs:
  test:
    name: TEST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build web
        env:
          TT: ${{ secrets.health_safety_url == null && 'nope' || secrets.health_safety_url }}
          TT2: ${{ env.TT }}
        run: echo ${{ env.TT2 }}


