name: TEST2

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  stg-cd:
    name: STG
    uses: ./.github/workflows/test.yml
    secrets:
      wp_host: 'host'
      health_safety_url: ${{ secrets.TEST_SECRET }}
