name: TEST

on:
  workflow_call:
    inputs:
      mode:
        type: string
        required: false
        default: 'production'
      version:
        type: string
        required: false
        default: ${{ github.sha }}
    secrets:
      wp_host:
        required: true
      health_safety_url:
        required: true

jobs:
  test:
    name: TEST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build web
        env:
          TT: ${{ secrets.health_safety_url == null && format('{0}/health-guidance-training-information', secrets.wp_host) || format('{0}/{1}', secrets.wp_host, secrets.health_safety_url) }}
        run: echo ${{ env.TT }}


