name: TEST

on:
  workflow_dispatch:
    secrets:
      wp_host: 'host'
      health_safety_url: ${{ secrets.TEST_SECRET }}

jobs:
  test:
    name: TEST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build web
        env:
          TT: ${{ secrets.health_safety_url == null && '${{ secrets.wp_host }}/health-guidance-training-information' || '${{ secrets.wp_host }}/${{ secrets.health_safety_url }}' }}
        run: echo ${{ env.TT }}


