name: TEST

on:
  workflow_dispatch:

jobs:
  test:
    name: TEST
    runs-on: ubuntu-latest

    env:
      TEST: ${{ secrets.TEST_SECRET }}
      TEST_NOT: ${{ secrets.TEST_SECRET_1 }}

    if: env.TEST == 'SECRET'
    run: echo ${{ env.TEST }}


