name: TEST

on:
  workflow_dispatch:

jobs:
  test:
    name: TEST
    runs-on: ubuntu-latest

    secrets:
      wp_host: 'host'
      health_safety_url: ${{ secrets.TEST_SECRET_1 }}

    env:
      TT: ${{ secrets.health_safety_url == null && '${{ secrets.wp_host }}/health-guidance-training-information' || '${{ secrets.wp_host }}/${{ secrets.health_safety_url }}' }}

    run: echo ${{ env.TT }}


